version: 2.1
orbs:
  codecov: codecov/codecov@3.3.0
jobs:
  build:
    working_directory: ~/treelock
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run: chmod +x ./gradlew
      - run: ./gradlew clean build test testCodeCoverageReport
      - codecov/upload:
          file: /**/test.exec

