version: 2.1
orbs:
  codecov: codecov/codecov@3.3.0
jobs:
  build:
    working_directory: ~/dlock
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: chmod +x ./gradlew
      - run: ./gradlew clean build codeCoverageReport
      - codecov/upload:
          file: /**/test.exec

