version: 2
jobs:
  build:
    working_directory: ~/dlock/dlock-spring
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: chmod +x ./gradlew
      - run: ./gradlew build
