package com.dlock.core.expiration

import com.dlock.core.model.ReadLockRecord

/**
 * Expires the lock when createdTime + expirationSeconds > NOW.
 * The NOW is provided by the lock itself (generated by the central repository, e.g. DB).
 */
class LocalLockExpirationPolicy() : LockExpirationPolicy {

    override fun expired(readLockRecord: ReadLockRecord): Boolean {
        return readLockRecord.createdTime
            .plusSeconds(readLockRecord.expirationSeconds)
            .isBefore(readLockRecord.currentTime)
    }

}