package dev.vavelin.treelock.api

/**
 * The handle is the main contract between the client (owner of the lock) and the lock provider.
 * It identifies the lock uniquely. Hence it contains enough information to represent a particular lock.
 *
 * @param handleId is like a secret, only owner of a lock knows it. It is generated by a generator.
 * Knowing the id you can break the lock.

 * @author Przemyslaw Malirz
 */
data class LockHandle(val handleId: String)